### ISSUE TITLE
Recent rebase breaks AUR package

### ISSUE THREAD

**Issue by lberrymage** [nullgemm/ly#220]
Since this only happened an hour ago I'm not sure exactly what's going on, but it appears that cylgom changed their username to nullgemm and then rebased all of their commits as the new username (please correcct me if I'm wrong). I'm sorry to say this really messes up package maintenance for me - I maintain the [ly-git AUR package](https://aur.archlinux.org/packages/ly-git/). It uses `git describe` to update the package version, but `git` is having problems finding tags to describe with. Even if this was fixed, the Arch User Repository may not recognize a package version as newer than another because the commit history is split into two.

@nullgemm, are you able to restore the previous commit history?

**Comment by nullgemm** [comment]
Hi, I can tag the last commit if it can help, but would like to avoid having to restore the previous history. I am very sorry about this.

**Comment by nullgemm** [comment]
@lberrymage The new tag fixed it for me, if it's ok I can promise this is the last time it ever happens and close the issue.

**Comment by lberrymage** [comment]
Thank you for your quick response. Yes, I think a new tag would work perfectly (and is much better than restoring history).

It's alright - such is life :grin:

**Comment by lberrymage** [comment]
I'll check the package really quick to be sure, but I think we're golden.

**Comment by lberrymage** [comment]
It works! Thank you again for jumping on this so quickly - I (and the AUR users) really appreciate it.
