### ISSUE TITLE
make error, missing "argoat.h"

### ISSUE THREAD

**Issue by bokunodev** [nullgemm/ly#223]
uname -r : `5.3.0-rc8-0.8-MANJARO-ARM`
gcc --version : `gcc (GCC) 9.2.0`
make --version : `GNU Make 4.3`
```
building object obj/src/main.o
src/main.c:1:10: fatal error: argoat.h: No such file or directory
    1 | #include "argoat.h"
      |          ^~~~~~~~~~
compilation terminated.
make: *** [makefile:52: obj/src/main.o] Error 1
```

**Comment by nullgemm** [comment]
Hi, please read the compilation instructions in the readme :)

**Comment by hholst80** [comment]
FYI this package uses submodules... the bane of sanity.
