### ISSUE TITLE
dwm on FreeBSD works well

### ISSUE THREAD

**Issue by plasmoduck** [nullgemm/ly#235]
I'd like to report that it works well with dwm on FreeBSD.

**Comment by schijtreiger** [comment]
What GPU/vga do you use? Having issues getting Ly to work right with an NVidia card...

**Comment by plasmoduck** [comment]
It's a late 2012 27" iMac with an Intel Core i5, 16gb ram and Nvisia GTX 660m. I use the 3**.*** nvidia driver from FreeBSD pkgs

**Comment by coughingmouse** [comment]
I also happen to be trying out `dwm`, but on VirtualBox. It seemingly works fine on my install as well. 

However, on my FreeBSD install, `ly` initiated by `/etc/ttys`  cannot shutdown nor reboot with neither `F1` nor `F2` (unlike when simply `doas ly`-ed in `zsh`).
Also, cursor disappears after pressing `enter` and does not come back even after coming back to `ly` by closing window manager. Is this happening to just me?

**Comment by plasmoduck** [comment]
Not to me

**Comment by plasmoduck** [comment]
See my other idea https://github.com/nullgemm/ly/issues/236
