### ISSUE TITLE
ly only runs on tty2

### ISSUE THREAD

**Issue by andersfylling** [nullgemm/ly#254]
I changed the config.ini to:
tty = 1

but ly only seem to run at tty2 (not 1. Also tested on tty3)

**Comment by kdkasad** [comment]
How are you invoking ly? Try the following:
```
# agetty -n -l /usr/bin/ly tty1 38400 linux
```
Replace `/usr/bin/ly` with the path to `ly`.  
Replace `tty1` with the TTY you want to use.

**Comment by PanayotisManganaris** [comment]
I am also having this problem.

**Comment by PanayotisManganaris** [comment]
I fixed this by modifying the lines referencing tty2 in `res/ly.service` to reference tty1.

**Comment by FadhilAF** [comment]
can i know how to change res/ly.service? it says permission denied even with sudo

**Comment by FadhilAF** [comment]
May i know where is that res/ly.service file located at?

**Comment by PanayotisManganaris** [comment]
https://github.com/nullgemm/ly/blob/master/res/ly.service

I modified it in my local clone of the repository. I then installed ly from source.

**Comment by pirog-x** [comment]
> res/ly.service

Type the command, and you will figure it out  ;)

```bash
$ systemctl status ly.service
```
```bash
● ly.service - TUI display manager
     Loaded: loaded (/usr/lib/systemd/system/ly.service; enabled; preset: disabled)
     Active: active (running) since Fri 2023-12-15 10:20:55 CET; 3min 56s ago
   Main PID: 9986 (ly)
      Tasks: 1 (limit: 17773)
     Memory: 376.0K
        CPU: 115ms
     CGroup: /system.slice/ly.service
             └─9986 /usr/bin/ly

Dec 15 10:20:55 fedora systemd[1]: Started ly.service - TUI display manager.
```
