### ISSUE TITLE
Question: Color scheme

### ISSUE THREAD

**Issue by rubenkharel** [nullgemm/ly#260]
Which file is responsible for the colors?
I want to modify it a bit with gruvbox scheme.

**Comment by rubenkharel** [comment]
Nvm, I found it, there is `config.ini.` inside `res` directory.

**Comment by ThatOneCalculator** [comment]
Wait, how did you do it? In `config.ini`, I see 
```
# background color id
#bg = 0
```, but no way to set hex codes or anything.

**Comment by ArchKubi** [comment]
> Nvm, I found it, there is `config.ini.` inside `res` directory.

![2022-04-27-210735_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/165591393-a3c2bfd3-6afb-495c-a31a-8adabee12ad5.png)
are you sure ?
