### ISSUE TITLE
ly does not start

### ISSUE THREAD

**Issue by ramezhammad** [nullgemm/ly#263]
ly does not start on any tty, i have to manually start it by typing ` ly ` , after it starts it shows this message: ` failed to access console `.

**Comment by markstos** [comment]
@ramezhammad You should report the version of `ly` you tried, along with your operating system name and version. Also, confirm if you are using `systemd` or another init system. Did you install  `ly` from a package or some other way?

**Comment by ramezhammad** [comment]
Version of ly: latest version
OS: Fedora 33
init system: systemd

ly compiled from source

**Comment by markstos** [comment]
Do you see errors in the system journal after  it fails to automatically start using journalctl ?

**Comment by ramezhammad** [comment]
i fixed it by uninstalling and reinstalling ly and the dependencies and updating my system.
