### ISSUE TITLE
awesome WM doesn't start

### ISSUE THREAD

**Issue by dhalucario** [nullgemm/ly#269]
awesome WM is shown in ly but after logging in all I see is a blinking cursor.

OS: Fedora 33 "Everything" (See https://alt.fedoraproject.org/)
Additional Repos: RPMFusion
Packages:
`@base-x` `awesome`
`akmod-nvidia` `xorg-x11-drv-nvidia-cuda`

**Comment by eZeDevelop** [comment]
I had a similar problem, see  #211. It could be SELinux preventing ly to start the WM.

**Comment by dhalucario** [comment]
It is, let me close this issue and move to #211
