### ISSUE TITLE
ly fails to start xorg

### ISSUE THREAD

**Issue by hellisabove** [nullgemm/ly#289]
I'm on arch and after installing, ly won't start any session. It will just say failed to start xorg and leave with a pointer on a useless terminal.

**Comment by AnErrupTion** [comment]
I'm on Arch and don't get this issue. What exactly happens?

**Comment by hellisabove** [comment]
It logs me in but every session fails to start xorg server

**Comment by AnErrupTion** [comment]
Did this happen wtih any other display manager?

**Comment by hellisabove** [comment]
No. every manager I use like sddm or gdm or lightdm work perfectly fine

**Comment by AnErrupTion** [comment]
This will be complicated without any details or logs. If you can concentrate, what can you see after you hit Enter when trying to log in? Like what exact error message does it show? I'll need this to further investigate.

**Comment by hellisabove** [comment]
Well I see the xorg server trying to start like if I was using startx but it just fails. It says xorg server failed to start and then leaves me with a cursor.

**Comment by AnErrupTion** [comment]
Do you have any DE installed or not?

**Comment by hellisabove** [comment]
I have gnome, kde and dwm

**Comment by hellisabove** [comment]
even tried on another laptop with a fresh install

**Comment by AnErrupTion** [comment]
Is it any flavour of Arch or pure Arch? It works for me with pure Arch.

**Comment by hellisabove** [comment]
pure

**Comment by AnErrupTion** [comment]
How did you install Ly?

**Comment by hellisabove** [comment]
from source. followed the instructions and i thought i was doing something wrong so I tried the aur version but the same problem

**Comment by AnErrupTion** [comment]
There's clearly some problem here. Now, I don't know if this will solve anything (perhaps it will?), try my Ly fork by installing it from the AUR : `ly-plank-patched`.

**Comment by hellisabove** [comment]
Thanks, now it works

**Comment by AnErrupTion** [comment]
Nice, glad it solved the problem! The fork only sets one (just a tiny one) environment variable, XDG_SESSION_TYPE properly (if you're curious).
