### ISSUE TITLE
xinitrc not working

### ISSUE THREAD

**Issue by Mihail-Bogdanov** [nullgemm/ly#318]
I'm using the AUR (ly-git) version and, for some reason, when i try to login with the xinitrc option (since ratpoison is not supported by ly) it quickly reloads and prompts me back to the display manager even if I typed my password correctly. Before you ask, I have added the line "exec retpoison" to my xinitrc

**Comment by alek3y** [comment]
You need to make .xinitrc executable and preferably add a shebang https://github.com/nullgemm/ly/issues/181#issuecomment-596244546.

**Comment by Mihail-Bogdanov** [comment]
> You need to make .xinitrc executable and preferably add a shebang [#181 (comment)](https://github.com/nullgemm/ly/issues/181#issuecomment-596244546).

made xinitrc executable and its working fine. Thanks!
